/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas;

import java.awt.Color;
import java.awt.Font;
import static java.awt.font.TextAttribute.FONT;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author baske
 */
public class Ajustes extends javax.swing.JPanel {

    /**
     * Creates new form Ajustes
     */
    public Ajustes() {
        initComponents();
        AdValores.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbObjetivo = new javax.swing.JLabel();
        ObjetivoDiario = new javax.swing.JTextField();
        LogoBasesDatos = new javax.swing.JLabel();
        TitAjustes = new javax.swing.JLabel();
        PanelCambiar = new javax.swing.JPanel();
        Cambiar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AdValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbObjetivo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        LbObjetivo.setText("Establecer Objetivo Diario");
        jPanel1.add(LbObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 184, 50));

        ObjetivoDiario.setBorder(null);
        ObjetivoDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObjetivoDiarioMouseClicked(evt);
            }
        });
        ObjetivoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetivoDiarioActionPerformed(evt);
            }
        });
        jPanel1.add(ObjetivoDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, 20));

        LogoBasesDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/img/Ajustes.png"))); // NOI18N
        jPanel1.add(LogoBasesDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 381, 192, 213));

        TitAjustes.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        TitAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitAjustes.setText("AJUSTES");
        jPanel1.add(TitAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, -1));

        PanelCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCambiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCambiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCambiarMouseExited(evt);
            }
        });

        Cambiar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Cambiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cambiar.setText("CAMBIAR");
        Cambiar.setOpaque(true);

        javax.swing.GroupLayout PanelCambiarLayout = new javax.swing.GroupLayout(PanelCambiar);
        PanelCambiar.setLayout(PanelCambiarLayout);
        PanelCambiarLayout.setHorizontalGroup(
            PanelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cambiar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCambiarLayout.setVerticalGroup(
            PanelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 170, 10));

        AdValores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdValoresMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Valores numericos");

        javax.swing.GroupLayout AdValoresLayout = new javax.swing.GroupLayout(AdValores);
        AdValores.setLayout(AdValoresLayout);
        AdValoresLayout.setHorizontalGroup(
            AdValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        AdValoresLayout.setVerticalGroup(
            AdValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(AdValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ObjetivoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetivoDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObjetivoDiarioActionPerformed

    private void PanelCambiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCambiarMouseEntered
        Cambiar.setFont(new Font("Roboto",Font.BOLD,20));
        Cambiar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelCambiarMouseEntered

    private void PanelCambiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCambiarMouseExited
        Cambiar.setFont(new Font("Roboto",Font.PLAIN,18));
        Cambiar.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_PanelCambiarMouseExited

    private void ObjetivoDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObjetivoDiarioMouseClicked

    }//GEN-LAST:event_ObjetivoDiarioMouseClicked

    private void PanelCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCambiarMouseClicked
        tomarNumero();
        
    }//GEN-LAST:event_PanelCambiarMouseClicked

    private void AdValoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdValoresMouseClicked
        AdValores.setVisible(false);
    }//GEN-LAST:event_AdValoresMouseClicked

    public void tomarNumero() {
        String expReg = "^(\\d{1,}$)|(^\\d{1,}(,|\\.)\\d{1,}$)";
        try {
            FileWriter escritor = new FileWriter(".\\src\\tools\\etc\\ObjetivoDiario\\ObjetivoCal.txt");
            if (ObjetivoDiario.getText().matches(expReg)) {
                escritor.write(ObjetivoDiario.getText());
                escritor.close();
                ObjetivoDiario.setText("");
                AdValores.setVisible(false);
            } else {
                System.out.println("Texto no valido, solo numeros");
                escritor.close();
                AdValores.setVisible(true);
                
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Ruta no encontrada");
        } catch (IOException e) {
            System.out.println("Error con el escritor de objetivo calorico");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdValores;
    private javax.swing.JLabel Cambiar;
    private javax.swing.JLabel LbObjetivo;
    private javax.swing.JLabel LogoBasesDatos;
    private javax.swing.JTextField ObjetivoDiario;
    private javax.swing.JPanel PanelCambiar;
    private javax.swing.JLabel TitAjustes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
