/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas;

import Data.FicheroDia;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;

/**
 *
 * @author baske
 */
public class InicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesion
     */
    private boolean placeholderUser = true;//booleano para controlar el placeholder del texto usuario
    private boolean placeholderMouse = true;//booleano para controlar el placeholder del texto contraseña
    private boolean userInfo = false;
    public InicioSesion() {
        initComponents();
        aplicarTransparencia();
        AdActualizado.setVisible(false);
        AdError.setVisible(false);

        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloInicioSesion = new javax.swing.JLabel();
        SubTitUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CampoUsuario = new javax.swing.JTextField();
        SubTitContra = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CampoContra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        JavaIcon = new javax.swing.JLabel();
        NetBeansIcon = new javax.swing.JLabel();
        GithubIcon = new javax.swing.JLabel();
        Disclaimer = new javax.swing.JLabel();
        PanelAcceder = new javax.swing.JPanel();
        TxtAcceder = new javax.swing.JLabel();
        AdActualizado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdError = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lema = new javax.swing.JPanel();
        TextoDiario1 = new javax.swing.JLabel();
        TextoDiario = new javax.swing.JLabel();
        LogoInicio = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloInicioSesion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TituloInicioSesion.setText("INICIAR SESION");
        jPanel1.add(TituloInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 60));

        SubTitUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SubTitUsuario.setText("Usuario");
        jPanel1.add(SubTitUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 63, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 159, 10));

        CampoUsuario.setText("Nombre usuario");
        CampoUsuario.setBorder(null);
        CampoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoUsuarioMouseClicked(evt);
            }
        });
        CampoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(CampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 154, 24));

        SubTitContra.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SubTitContra.setText("Contraseña");
        jPanel1.add(SubTitContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 159, 10));

        CampoContra.setText("* * * * * * * *");
        CampoContra.setBorder(null);
        CampoContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoContraMouseClicked(evt);
            }
        });
        CampoContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoContraActionPerformed(evt);
            }
        });
        CampoContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoContraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoContraKeyTyped(evt);
            }
        });
        jPanel1.add(CampoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 154, 25));

        JavaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/img/java.png"))); // NOI18N

        NetBeansIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/img/netbeans.png"))); // NOI18N

        GithubIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/img/github.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GithubIcon)
                    .addComponent(JavaIcon)
                    .addComponent(NetBeansIcon))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(GithubIcon)
                .addGap(24, 24, 24)
                .addComponent(NetBeansIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JavaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 230, -1));

        Disclaimer.setText("Proyecto personal Raul Val Iturbide");
        jPanel1.add(Disclaimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        PanelAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAccederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAccederMouseExited(evt);
            }
        });

        TxtAcceder.setBackground(new java.awt.Color(255, 255, 255));
        TxtAcceder.setForeground(new java.awt.Color(51, 51, 51));
        TxtAcceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtAcceder.setText("ENTRAR");

        javax.swing.GroupLayout PanelAccederLayout = new javax.swing.GroupLayout(PanelAcceder);
        PanelAcceder.setLayout(PanelAccederLayout);
        PanelAccederLayout.setHorizontalGroup(
            PanelAccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAccederLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TxtAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelAccederLayout.setVerticalGroup(
            PanelAccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAccederLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(PanelAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario actualizado");

        javax.swing.GroupLayout AdActualizadoLayout = new javax.swing.GroupLayout(AdActualizado);
        AdActualizado.setLayout(AdActualizadoLayout);
        AdActualizadoLayout.setHorizontalGroup(
            AdActualizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        AdActualizadoLayout.setVerticalGroup(
            AdActualizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(AdActualizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 180, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rellene ambos campos");

        javax.swing.GroupLayout AdErrorLayout = new javax.swing.GroupLayout(AdError);
        AdError.setLayout(AdErrorLayout);
        AdErrorLayout.setHorizontalGroup(
            AdErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        AdErrorLayout.setVerticalGroup(
            AdErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(AdError, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 160, 60));

        TextoDiario1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        TextoDiario1.setText("LAS CALORIAS CUENTAN");
        TextoDiario1.setToolTipText("");

        TextoDiario.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        TextoDiario.setText("NOSOTROS LAS CALCULAMOS");
        TextoDiario.setToolTipText("");

        javax.swing.GroupLayout LemaLayout = new javax.swing.GroupLayout(Lema);
        Lema.setLayout(LemaLayout);
        LemaLayout.setHorizontalGroup(
            LemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LemaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(LemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LemaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(TextoDiario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextoDiario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        LemaLayout.setVerticalGroup(
            LemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LemaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoDiario1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoDiario)
                .addGap(25, 25, 25))
        );

        jPanel1.add(Lema, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, 50));

        LogoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/img/vegetariano3.png"))); // NOI18N
        jPanel1.add(LogoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoUsuarioMouseClicked
       if(placeholderUser){
        CampoUsuario.setText("");
        placeholderUser = false;
        CampoUsuario.setForeground(new Color(0, 0, 0, 200));
       }
    }//GEN-LAST:event_CampoUsuarioMouseClicked

    private void CampoContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoContraMouseClicked
        if(placeholderMouse){
        CampoContra.setText("");
        placeholderMouse = false;
        CampoContra.setForeground(new Color(0, 0, 0, 200));
       }
    }//GEN-LAST:event_CampoContraMouseClicked

    private void PanelAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAccederMouseEntered
        TxtAcceder.setForeground(new Color(255,255,255));
        TxtAcceder.setFont(new Font("Roboto",Font.BOLD,12));
    }//GEN-LAST:event_PanelAccederMouseEntered

    private void PanelAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAccederMouseExited
        TxtAcceder.setForeground(new Color(0,0,0));
        TxtAcceder.setFont(new Font("Roboto",Font.PLAIN,12));
    }//GEN-LAST:event_PanelAccederMouseExited

    private void CampoContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoContraKeyTyped
        
    }//GEN-LAST:event_CampoContraKeyTyped

    private void CampoContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoContraKeyPressed
       
    }//GEN-LAST:event_CampoContraKeyPressed

    private void CampoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioKeyTyped

    private void PanelAccederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAccederMouseClicked
        ventanaEmergente();


      
    }//GEN-LAST:event_PanelAccederMouseClicked

    private void CampoContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraActionPerformed
    
    public void comprobarInfoUser(){
        
        try{
        FileWriter escritor = new FileWriter(".\\src\\tools\\etc\\User\\data.txt");
        escritor.write(CampoUsuario.getText() + "\n");
        escritor.write(CampoContra.getText() + "\n");
        escritor.close();
        }catch(FileNotFoundException ex){
            System.out.println("Error encontrando la ruta del txt data");
        }catch(IOException e){
            System.out.println("Error fatal en el escritor de comprobarInfoUser");
        }
        
        }
    /**
     * Este metodo pretende sacar una ventana dependiendo de si el usuario mete la informacion de manera correcta o incorrecta
     * actualizando el usuario si se han metido todos los datos indispensables
     */
    public void ventanaEmergente() {
        if (CampoUsuario.getText().equals("") || CampoContra.getText().equals("") || CampoUsuario.getText().equals("Nombre usuario") || CampoContra.getText().equals("* * * * * * * *")) {
            AdActualizado.setVisible(false);
            AdError.setVisible(true);
            System.out.println("Error texto : " + CampoUsuario.getText());    
        } else {
            AdError.setVisible(false);
            AdActualizado.setVisible(true);
            userInfo = true;
            System.out.println("Correcto texto : " + CampoUsuario.getText());
              comprobarInfoUser();
        }
      
        CampoContra.setText("");
        CampoUsuario.setText("");
        
    }
    
    /**
     * Este metodo se incia al principio para establecer los campos de texto con una transparencia como un placeholder
     */
    
    public void aplicarTransparencia(){
         CampoUsuario.setForeground(new Color(0, 0, 0, 128));
         CampoContra.setForeground(new Color(0, 0, 0, 128));
         Disclaimer.setForeground(new Color(0, 0, 0, 128));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdActualizado;
    private javax.swing.JPanel AdError;
    private javax.swing.JTextField CampoContra;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JLabel Disclaimer;
    private javax.swing.JLabel GithubIcon;
    private javax.swing.JLabel JavaIcon;
    private javax.swing.JPanel Lema;
    private javax.swing.JLabel LogoInicio;
    private javax.swing.JLabel NetBeansIcon;
    private javax.swing.JPanel PanelAcceder;
    private javax.swing.JLabel SubTitContra;
    private javax.swing.JLabel SubTitUsuario;
    private javax.swing.JLabel TextoDiario;
    private javax.swing.JLabel TextoDiario1;
    private javax.swing.JLabel TituloInicioSesion;
    private javax.swing.JLabel TxtAcceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
